version: '3.8'

services:
  flask:
    build: ./admin_interface
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - ./admin_interface:/app
      - modsec-logs:/mnt/modsec-logs:ro
      - firewall-logs:/mnt/firewall-logs:ro
      - nginx-logs:/mnt/nginx-logs:ro
      - ./firewall/config/nftables.conf:/mnt/firewall-config/nftables.conf
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=flask_db

  db:
    image: mysql:8.0
    container_name: mysql-flask
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

  waf:
    build: ./waf
    ports:
      - "80:80"
    volumes:
      - ./waf/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./waf/config/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf:ro
      - ./waf/config/crs-setup.conf:/usr/local/modsecurity-crs/crs-setup.conf:ro
      - ./waf/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - modsec-logs:/var/log
      - nginx-logs:/var/log/nginx
    depends_on:
      - flask

  firewall:
    build: ./firewall
    ports:
      - "3001:80"
    volumes:
      - ./firewall/config/nftables.conf:/etc/nftables.conf:ro
      - firewall-logs:/var/log

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"

volumes:
  db_data:
  modsec-logs:
  firewall-logs:
  nginx-logs:
